/* ============================================================
   data.js — 85 个经典股票模型
   每条模型 = { id, name, alias, cat, gen, src, one, looks[], vol[],
                mech, buy, stop, fail[], pitfall[], related[] }
   gen 字段对应 candles.js 里的 CANDLE_GEN.<name> 生成器。
   ============================================================ */
(function (global) {
  "use strict";

  // label：筛选/角标上显示的"大白话"；hint：悬停解释（含术语原文，帮小白建立词汇）
  const CATEGORIES = [
    { key: "reversal",     label: "见顶见底", color: "var(--cat-reversal)",
      hint: "见顶见底（术语：反转形态）——出现在一段涨/跌的末端，预示趋势可能掉头。如头肩顶、双底、V形反转。" },
    { key: "continuation", label: "中途整理", color: "var(--cat-continue)",
      hint: "中途整理（术语：持续形态）——趋势中途的歇脚，如杯柄、旗形、三角形，歇完多半延续原方向。" },
    { key: "single",       label: "单根K线", color: "var(--cat-single)",
      hint: "单根K线（术语：单根蜡烛）——只看一根K线的形状判断转折，如锤子线、十字星、流星线。" },
    { key: "two",          label: "两根K线", color: "var(--cat-two)",
      hint: "两根K线（术语：双蜡烛组合）——相邻两根组合判断，如看涨吞没、乌云盖顶、孕线。" },
    { key: "three",        label: "三根K线", color: "var(--cat-three)",
      hint: "三根K线（术语：三蜡烛组合）——三根组合判断，如晨星、黄昏星、红三兵、上升三法。" },
    { key: "gap",          label: "跳空缺口", color: "var(--cat-gap)",
      hint: "跳空缺口——开盘价和昨日不连续、中间留有断层，分突破缺口/中继缺口/衰竭缺口。" },
    { key: "system",       label: "名家战法", color: "var(--cat-system)",
      hint: "名家战法与指标——利弗莫尔关键点、威科夫吸筹派发、缠论、波浪理论、葛兰碧八法则，以及均线/MACD/布林/海龟等指标。" }
  ];

  const S = {
    oneil:  "欧奈尔《笑傲股市》",
    liver:  "利弗莫尔《股票作手回忆录》",
    nison:  "尼森《日本蜡烛图技术》",
    wyk:    "威科夫方法",
    chan:   "缠中说禅《缠论》",
    ellio:  "艾略特《波浪理论》",
    gran:   "葛兰碧均线八法则",
    boll:   "布林带(John Bollinger)",
    turtle: "海龟交易法/唐奇安通道",
    gann:   "江恩理论",
    clas:   "经典技术分析/道氏"
  };

  const MODELS = [

  /* ================= 反转形态 — 顶部 ================= */
  { id:"head_shoulders_top", name:"头肩顶", alias:"Head & Shoulders Top", cat:"reversal", gen:"head_shoulders_top", src:S.clas,
    one:"最可靠的主跌反转形态：三个峰，中间最高(头)，两侧相近(肩)，跌破颈线确认。",
    looks:["左肩—头部—右肩三峰，头部最高、两肩大致等高且偏低","两肩之间的两个回调低点连线即'颈线'","右肩成交量通常小于左肩与头部"],
    vol:["头部成交量最大，右肩明显缩量","跌破颈线时可放量，也可缩量","跌破后回抽颈线常缩量"],
    mech:"主力在头部派发：头部吸引追高盘放量出货，右肩缩量说明买力衰竭，颈线失守即抛压接管。",
    buy:"—（顶部反转，做空/减仓信号）", stop:"放量跌破颈线做空，止损放在右肩高点上方",
    fail:["右肩突破头部新高→形态失败","跌破颈线后快速收回颈线上方=假突破","右肩放量创新高则不是头肩顶"],
    pitfall:["颈线未跌破前不能算确认，'画在纸上'的头肩顶最危险","颈线斜率向上比向下更弱","把任何三峰都叫头肩顶"],
    related:["double_top","head_shoulders_bottom","double_bottom"] },

  { id:"double_top", name:"双顶", alias:"M头 / Double Top", cat:"reversal", gen:"double_top", src:S.clas,
    one:"两个相近高点的反转形态，跌破中间回调低点(颈线)确认下跌。",
    looks:["两个高点大致等高，间隔数周到数月","第二峰成交量常小于第一峰","颈线=两峰之间最低点"],
    vol:["第二峰缩量是经典确认","跌破颈线时不必放量，放量更弱","回抽颈线常缩量"],
    mech:"第一峰主力出货，反弹至前高买力不足形成第二峰，颈线失守代表支撑被击穿。",
    buy:"—（做空/减仓）", stop:"跌破颈线做空，止损第二峰高点上方",
    fail:["第二峰放量突破第一峰→趋势继续","跌破颈线前反弹创新高=失败"],
    pitfall:["未跌破颈线就当双顶是常见错误","两峰间隔太近(几天)有效性差"],
    related:["triple_top","head_shoulders_top","double_bottom"] },

  { id:"triple_top", name:"三重顶", alias:"Triple Top", cat:"reversal", gen:"triple_top", src:S.clas,
    one:"三个相近高点的反转形态，比双顶多一次冲击，跌破支撑确认。",
    looks:["三个高点相近，间隔可数周","每个高点成交量递减更佳","支撑线=三次回调低点连线"],
    vol:["每次冲击高点量能递减","跌破支撑放量"],
    mech:"多次冲击同一阻力均告失败，说明买力持续衰减，支撑一旦失守抛压接管。",
    buy:"—（做空/减仓）", stop:"跌破支撑做空，止损最近高点上方",
    fail:["某次冲击放量突破高点→失败","跌破支撑后快速收回"],
    pitfall:["把横盘震荡的多次触顶都叫三重顶"],
    related:["double_top","rectangle_box"] },

  { id:"rounded_top", name:"圆弧顶", alias:"Rounding Top / 馏顶", cat:"reversal", gen:"rounded_top", src:S.clas,
    one:"价格缓慢上升后逐渐走平再缓慢回落形成的圆弧形顶部，过程温和、量缩。",
    looks:["顶部呈圆弧形，无明显尖峰","上升斜率递减→走平→下降斜率递增","形态耗时数周到数月"],
    vol:["攀升期放量，圆顶区缩量","下跌开始后量能渐增"],
    mech:"买力逐级衰竭、卖压逐级加重，主力缓慢派发，转折无声。",
    buy:"—（减仓/离场）", stop:"跌破圆弧右侧加速段加仓空，止损前高",
    fail:["圆顶右侧放量创新高则延续上涨"],
    pitfall:["圆弧形态耗时漫长，常被误判为震荡"],
    related:["v_top","diamond_top","rounded_bottom"] },

  { id:"v_top", name:"V形顶", alias:"尖顶 / V Top", cat:"reversal", gen:"v_top", src:S.clas,
    one:"急速拉升后见顶急速回落，呈V形倒转，转折猛烈、难预判。",
    looks:["左侧陡峭上升，顶部常带长上影或放量滞涨","右侧下跌速度与角度接近上升","转折极快，几乎无过渡"],
    vol:["见顶日常放天量或长上影","下跌起步即放量"],
    mech:"追高盘在顶部遭遇集中抛压，动能瞬间反转，常因利空或主力集中出货。",
    buy:"—（破位即减仓）", stop:"跌破起涨加速点止损，V顶难以左侧交易",
    fail:["尖顶后立刻V反再创新高=洗盘","右侧无量阴跌不一定是V顶"],
    pitfall:["试图在顶点做空极易被扎空","把普通震荡尖峰都当V顶"],
    related:["v_bottom","island_top"] },

  { id:"diamond_top", name:"菱形", alias:"扩散收敛顶 / Diamond", cat:"reversal", gen:"diamond_top", src:S.clas,
    one:"先扩散后收敛的菱形顶部，前半段波动放大、后半段收敛，跌破下沿确认。",
    looks:["左半扩散(高低点向外扩张)，右半收敛(向内收拢)","整体形如菱形/钻石","下沿即颈线"],
    vol:["扩散段放量且波动剧烈","收敛段量能递减","跌破下沿放量"],
    mech:"扩散反映多空分歧加大，收敛反映动能衰减，收敛末端方向选择向下即反转。",
    buy:"—（做空）", stop:"跌破菱形下沿做空，止损菱形上沿",
    fail:["收敛末端向上突破则延续"],
    pitfall:["菱形难辨认，常与对称三角形混淆"],
    related:["symmetric_triangle","broadening"] },

  { id:"island_top", name:"岛形反转顶", alias:"Island Reversal(顶)", cat:"reversal", gen:"island_top", src:S.clas,
    one:"一个被两侧缺口包围的'孤岛'K线群，右侧向下跳空缺口确认反转。",
    looks:["左侧向上跳空缺口把一段K线群隔离成岛","岛内数根K线窄幅整理","右侧向下跳空缺口封闭岛"],
    vol:["岛内缩量","右侧向下缺口常放量"],
    mech:"跳空形成孤岛说明情绪极端，缺口回补方向即反转方向，岛顶是 exhaustion 信号。",
    buy:"—（反转减仓/做空）", stop:"向下跳空缺口下沿做空，止损岛内高点",
    fail:["右侧缺口被快速回补且收回=假反转"],
    pitfall:["把普通跳空当岛形","岛内未形成整理而是趋势则不成立"],
    related:["exhaustion_gap","island_bottom"] },

  /* ================= 反转形态 — 底部 ================= */
  { id:"head_shoulders_bottom", name:"头肩底", alias:"头肩顶倒影 / Inverse H&S", cat:"reversal", gen:"head_shoulders_bottom", src:S.clas,
    one:"三个低谷，中间最低(头)、两侧相近(肩)，放量突破颈线确认反转上涨。",
    looks:["左肩—头部—右肩三谷，头部最低","颈线=两肩之间反弹高点连线","右肩缩量、突破颈线放量"],
    vol:["头部恐慌放量(抛压释放)","右肩缩量(卖压衰竭)","突破颈线放量是关键确认"],
    mech:"底部吸筹：头部恐慌盘被主力承接，右肩抛压衰竭，颈线突破标志买力接管。",
    buy:"放量突破颈线买入，或回踩颈线不破加仓", stop:"止损头部低点下方",
    fail:["跌破头部新低→形态失败","突破颈线后跌回颈线下方=假突破"],
    pitfall:["颈线未突破前不算确认","把三谷都叫头肩底"],
    related:["double_bottom","head_shoulders_top"] },

  { id:"double_bottom", name:"双底", alias:"W底 / Double Bottom", cat:"reversal", gen:"double_bottom", src:S.oneil,
    one:"两个相近低点形成W形，放量突破颈线(两底间反弹高点)确认上涨。欧奈尔CAN SLIM常见底部。",
    looks:["两个低点相近，第二底常略高或等高","颈线=两底间反弹高点","第二底缩量更佳"],
    vol:["第二底缩量(抛压衰竭)","突破颈线放量(50%以上更佳)","回踩颈线缩量"],
    mech:"第一底恐慌见底，反弹后回踩前低买盘承接，颈线突破确认反转。",
    buy:"突破颈线买入，回踩颈线不破加仓", stop:"跌破第二底低点止损",
    fail:["跌破第二底新低→失败","突破颈线后跌回颈线下方"],
    pitfall:["未突破颈线即进场易被套","第二底远低于第一底则偏弱"],
    related:["triple_bottom","cup_handle","head_shoulders_bottom"] },

  { id:"triple_bottom", name:"三重底", alias:"Triple Bottom", cat:"reversal", gen:"triple_bottom", src:S.clas,
    one:"三个相近低点的反转形态，多次考验支撑未破，突破颈线确认。",
    looks:["三个低点相近","颈线=三次反弹高点","第三次缩量最佳"],
    vol:["每次触底量能递减","突破颈线放量"],
    mech:"三次考验同一支撑均未破，说明卖压衰竭，颈线突破确认反转。",
    buy:"突破颈线买入", stop:"跌破三个低点止损",
    fail:["跌破支撑新低","突破颈线后跌回"],
    pitfall:["把横盘多次触底都叫三重底"],
    related:["double_bottom","rectangle_box"] },

  { id:"rounded_bottom", name:"圆弧底", alias:"碟形底 / Rounding Bottom", cat:"reversal", gen:"rounded_bottom", src:S.clas,
    one:"价格缓慢下跌后走平再缓慢上升形成的圆弧形底部，量缩到量增。",
    looks:["底部呈圆弧/碟形，无明显尖底","下跌斜率递减→走平→上升斜率递增","形态耗时数周到数月"],
    vol:["下跌末段与圆底区极度缩量","上升启动后量能渐增"],
    mech:"卖压逐级衰竭、买力逐级介入，主力缓慢收集，底部无声完成。",
    buy:"放量突破圆弧右侧加速段买入", stop:"止损圆弧最低点下方",
    fail:["圆底右侧放量跌破前低"],
    pitfall:["耗时漫长易被当震荡","圆底右侧无量则偏弱"],
    related:["v_bottom","rounding_breakout","rounded_top"] },

  { id:"v_bottom", name:"V形底", alias:"尖底 / V Bottom", cat:"reversal", gen:"v_bottom", src:S.clas,
    one:"急速下跌后见底急速反弹，呈V形，转折猛烈、常伴随恐慌与放量。",
    looks:["左侧陡峭下跌，底部常带长下影或放量","右侧反弹速度与角度接近下跌","转折极快"],
    vol:["见底日恐慌放量或长下影","反弹起步即放量"],
    mech:"恐慌盘集中释放后被主力承接，动能瞬间反转，常因利好或主力集中吸筹。",
    buy:"见底放量长下影/大阳后次日不创新低可试多", stop:"止损V底最低点下方",
    fail:["尖底后再次破低=延续下跌","右侧无量反弹弱"],
    pitfall:["试图在下跌中抄底极易深套","V底难左侧交易"],
    related:["v_top","island_bottom"] },

  { id:"island_bottom", name:"岛形反转底", alias:"Island Reversal(底)", cat:"reversal", gen:"island_bottom", src:S.clas,
    one:"被两侧缺口包围的孤岛K线群，右侧向上跳空缺口确认反转上涨。",
    looks:["左侧向下跳空缺口把一段K线群隔离成岛","岛内窄幅整理","右侧向上跳空缺口封闭岛"],
    vol:["岛内缩量","右侧向上缺口常放量"],
    mech:"跳空形成孤岛说明情绪极端，缺口回补方向即反转方向，岛底是见底信号。",
    buy:"右侧向上缺口确认后买入", stop:"止损岛内低点下方",
    fail:["右侧缺口被回补且跌回岛内=假反转"],
    pitfall:["把普通跳空当岛形"],
    related:["breakaway_gap","island_top"] },

  /* ================= 持续形态 ================= */
  { id:"ascending_triangle", name:"上升三角形", alias:"Ascending Triangle", cat:"continuation", gen:"ascending_triangle", src:S.clas,
    one:"水平阻力+上升支撑线收敛，多数向上突破，是强势持续形态。",
    looks:["顶部水平阻力线(多次触顶等高)","底部低点逐步抬高，连线为上升支撑线","两线收敛于顶点"],
    vol:["每次触顶量能递减","向上突破阻力时放量","回踩阻力缩量"],
    mech:"卖压固定在阻力位但买力逐步抬高，最终买力战胜卖压向上突破。",
    buy:"放量突破水平阻力买入，回踩阻力不破加仓", stop:"跌破上升支撑线止损",
    fail:["跌破上升支撑线→失败","突破阻力后跌回阻力下方=假突破"],
    pitfall:["未突破前在阻力下沿提前埋伏易被套","把下降三角形方向搞反"],
    related:["descending_triangle","symmetric_triangle"] },

  { id:"descending_triangle", name:"下降三角形", alias:"Descending Triangle", cat:"continuation", gen:"descending_triangle", src:S.clas,
    one:"水平支撑+下降阻力线收敛，多数向下突破，是弱势持续形态。",
    looks:["底部水平支撑线(多次触底等低)","顶部高点逐步降低，连线为下降阻力线","两线收敛"],
    vol:["每次触底量能递减","跌破支撑时放量","反抽支撑缩量"],
    mech:"买力固定在支撑位但卖压逐步加重，最终卖压战胜买力向下突破。",
    buy:"—（做空/回避）", stop:"放量跌破水平支撑做空，止损下降阻力线上方",
    fail:["突破下降阻力线向上→失败","跌破支撑后收回=假跌破"],
    pitfall:["把方向搞反成上升三角形"],
    related:["ascending_triangle","symmetric_triangle"] },

  { id:"symmetric_triangle", name:"对称三角形", alias:"Symmetric Triangle", cat:"continuation", gen:"symmetric_triangle", src:S.clas,
    one:"高点降低、低点抬高，两线收敛，方向待选择，顺原趋势突破概率大。",
    looks:["顶部高点逐步降低(下降阻力线)","底部低点逐步抬高(上升支撑线)","两线收敛于顶点"],
    vol:["形态内量能逐步萎缩","突破方向放量确认","越接近顶点突破越弱"],
    mech:"多空力量均衡收敛，动能积蓄，原趋势方向突破概率较大。",
    buy:"突破方向(配合原趋势)放量后跟进", stop:"跌破反向支撑/阻力止损",
    fail:["突破后快速回到三角形内=假突破","顶点处突破常失败"],
    pitfall:["提前猜方向","在形态内频繁交易"],
    related:["ascending_triangle","descending_triangle","bull_pennant"] },

  { id:"broadening", name:"扩散三角形", alias:"喇叭形 / Broadening", cat:"continuation", gen:"broadening", src:S.clas,
    one:"高点抬高、低点降低，两线向外扩张，波动放大，多出现在顶部、看跌。",
    looks:["顶部高点逐步抬高","底部低点逐步降低","两线向外扩散成喇叭"],
    vol:["波动放大、量能不稳","常出现在主升末段"],
    mech:"多空分歧剧烈加大、情绪失控，常为主升末段派发信号，方向偏空。",
    buy:"—（警惕/做空）", stop:"跌破下沿做空，止损最近高点上方",
    fail:["突破上沿放量创新高则延续"],
    pitfall:["把扩散当持续上涨信号"],
    related:["diamond_top","symmetric_triangle"] },

  { id:"bull_flag", name:"上升旗形", alias:"看涨旗形 / Bull Flag", cat:"continuation", gen:"bull_flag", src:S.oneil,
    one:"急升旗杆+小幅向下倾斜的旗面整理，放量突破旗面延续上涨。",
    looks:["前期急升构成旗杆(成交量放大)","旗面为小幅向下倾斜的平行通道(回撤浅)","旗面时间短于旗杆"],
    vol:["旗杆放量","旗面缩量(回撤浅、量缩)","突破旗面放量"],
    mech:"急升后短线获利盘回吐，回撤浅说明卖压轻，突破即趋势延续。",
    buy:"放量突破旗面上沿买入", stop:"跌破旗面下沿止损",
    fail:["跌破旗面下沿=形态失败","回撤过深(超过旗杆1/2)则偏弱"],
    pitfall:["回撤过深仍当旗形","旗杆无量则形态无力"],
    related:["bear_flag","bull_pennant","high_tight_flag"] },

  { id:"bear_flag", name:"下降旗形", alias:"看跌旗形 / Bear Flag", cat:"continuation", gen:"bear_flag", src:S.clas,
    one:"急跌旗杆+小幅向上倾斜的旗面整理，跌破旗面延续下跌。",
    looks:["前期急跌构成旗杆","旗面为小幅向上倾斜的平行通道(反弹弱)","旗面缩量"],
    vol:["旗杆放量下跌","旗面缩量反弹","跌破旗面放量"],
    mech:"急跌后短线反弹乏力，反弹弱说明买力轻，跌破即趋势延续下跌。",
    buy:"—（做空/回避）", stop:"跌破旗面下沿做空，止损旗面上沿上方",
    fail:["突破旗面上沿=失败","反弹过强则偏弱"],
    pitfall:["把熊旗当见底反弹"],
    related:["bull_flag","bear_pennant"] },

  { id:"bull_pennant", name:"看涨三角旗", alias:"Bull Pennant", cat:"continuation", gen:"bull_pennant", src:S.clas,
    one:"急升旗杆+小型对称三角形整理，缩量到极致后放量突破延续上涨。",
    looks:["前期急升旗杆","旗面为小型对称三角形(收敛)","量能极度萎缩"],
    vol:["旗杆放量","三角形内量能递减到地量","突破放量"],
    mech:"急升后多空短暂均衡收敛，量能枯竭后选择方向向上。",
    buy:"放量突破三角形上沿买入", stop:"跌破三角形下沿止损",
    fail:["跌破下沿=失败","顶点处突破常无力"],
    pitfall:["与楔形混淆"],
    related:["bear_pennant","bull_flag","symmetric_triangle"] },

  { id:"bear_pennant", name:"看跌三角旗", alias:"Bear Pennant", cat:"continuation", gen:"bear_pennant", src:S.clas,
    one:"急跌旗杆+小型对称三角形整理，缩量后跌破延续下跌。",
    looks:["前期急跌旗杆","旗面为小型对称三角形(收敛)","量能萎缩"],
    vol:["旗杆放量下跌","三角形内缩量","跌破放量"],
    mech:"急跌后多空短暂均衡收敛，量能枯竭后选择方向向下。",
    buy:"—（做空/回避）", stop:"跌破三角形下沿做空，止损上沿上方",
    fail:["突破上沿=失败"],
    pitfall:["与上升楔形混淆"],
    related:["bull_pennant","bear_flag"] },

  { id:"rising_wedge", name:"上升楔形", alias:"Rising Wedge", cat:"continuation", gen:"rising_wedge", src:S.clas,
    one:"高点与低点同步抬高但收敛向上，动能递减，多数向下突破(反转/看跌)。",
    looks:["高点逐步抬高(上轨)、低点逐步抬高(下轨)","两轨向上收敛","楔形内成交量递减"],
    vol:["形态内量能递减","跌破下轨放量"],
    mech:"上涨动能递减、每次新高买力不足，收敛末端跌破下轨看跌。",
    buy:"—（警惕/做空）", stop:"跌破下轨做空，止损上轨上方",
    fail:["放量突破上轨则延续上涨"],
    pitfall:["把上升楔形当持续强势"],
    related:["falling_wedge","symmetric_triangle"] },

  { id:"falling_wedge", name:"下降楔形", alias:"Falling Wedge", cat:"continuation", gen:"falling_wedge", src:S.clas,
    one:"高点与低点同步降低但收敛向下，跌势动能递减，多数向上突破(看涨)。",
    looks:["高点逐步降低(上轨)、低点逐步降低(下轨)","两轨向下收敛","楔形内成交量递减"],
    vol:["形态内量能递减","突破上轨放量"],
    mech:"下跌动能递减、每次新低卖压不足，收敛末端突破上轨看涨。",
    buy:"放量突破上轨买入", stop:"跌破下轨止损",
    fail:["跌破下轨加速下跌则失败"],
    pitfall:["把下降楔形当持续弱势"],
    related:["rising_wedge","symmetric_triangle"] },

  { id:"rectangle_box", name:"矩形/箱体", alias:"Rectangle / Box", cat:"continuation", gen:"rectangle_box", src:S.clas,
    one:"价格在水平支撑与阻力间来回震荡，突破方向延续原趋势。",
    looks:["水平阻力线与水平支撑线","价格在两线间来回多次","形态内量能递减"],
    vol:["形态内量能递减","突破方向放量","回踩突破线缩量"],
    mech:"多空在固定区间内博弈，量能递减表明积蓄，突破方向即趋势延续。",
    buy:"放量突破箱体上沿买入(顺势)，回踩不破加仓", stop:"跌破箱体下沿止损",
    fail:["突破后快速回到箱体内=假突破","反复假突破消耗"],
    pitfall:["在箱体内频繁高抛低吸易被突破打穿","提前猜方向"],
    related:["flat_base","triple_top","triple_bottom"] },

  { id:"cup_handle", name:"杯柄形态", alias:"Cup and Handle", cat:"continuation", gen:"cup_handle", src:S.oneil,
    one:"欧奈尔《笑傲股市》经典：U形杯+浅幅回撤柄，放量突破杯沿即主升买点。",
    looks:["杯呈U形(非V形)，左沿到右沿大致等高","杯底圆滑、回调幅度约12-25%(不超1/3)","柄为浅幅回撤(5-15%)的小幅下行，时间1-4周"],
    vol:["杯左沿放量下跌(恐慌)、杯底缩量","右沿放量回升","柄缩量、突破杯沿放量(较均量放大50%以上)"],
    mech:"左沿高点主力洗盘，杯底缩量筹码稳定，右沿回升买力回归，柄为最后一次洗盘，突破即主升。",
    buy:"放量突破杯沿高点(柄区上沿)买入", stop:"止损柄区低点下方",
    fail:["柄回撤过深(超杯高的1/3)或跌破杯沿","杯呈V形而非U形则偏弱","突破杯沿不放量则偏弱"],
    pitfall:["柄中提前埋伏易被洗","把V形底当杯柄","杯沿未放量突破就进场"],
    related:["double_bottom","high_tight_flag","flat_base"] },

  { id:"flat_base", name:"平底/平基", alias:"Flat Base", cat:"continuation", gen:"flat_base", src:S.oneil,
    one:"欧奈尔CAN SLIM第二阶段：窄幅横盘5-6周、回调浅(10-15%)、量缩，突破延续主升。",
    looks:["价格窄幅横盘5-6周或更长","回调幅度浅(一般10-15%)","横盘期成交量递减"],
    vol:["横盘期量能萎缩","突破平台放量"],
    mech:"主升后中途休整、筹码沉淀，缩量横盘表明卖压轻，放量突破延续趋势。",
    buy:"放量突破平台高点买入", stop:"跌破平台下沿止损",
    fail:["跌破平台下沿=失败","突破不放量则偏弱"],
    pitfall:["横盘过久(超半年)动能流失","未突破提前埋伏"],
    related:["cup_handle","rectangle_box","high_tight_flag"] },

  { id:"high_tight_flag", name:"高窄旗形", alias:"High Tight Flag", cat:"continuation", gen:"high_tight_flag", src:S.oneil,
    one:"欧奈尔最强形态：短期暴涨100-120%后窄幅横盘3-5周，突破后常翻倍。",
    looks:["旗杆短期暴涨约100-120%","旗面极窄幅横盘(回撤不超20%)3-5周","旗面时间短"],
    vol:["旗杆连续放量暴涨","旗面缩量横盘","突破旗面放量"],
    mech:"极强买力短期暴涨后强势横盘消化，突破即二次主升，常见于领涨龙头。",
    buy:"放量突破旗面上沿买入", stop:"止损旗面下沿",
    fail:["跌破旗面下沿=失败","旗杆涨幅不足则力度弱"],
    pitfall:["涨幅不足100%却当高窄旗","回撤过深"],
    related:["bull_flag","cup_handle","flat_base"] },

  { id:"rounding_breakout", name:"潜伏底突破", alias:"平台突破 / Dormant Bottom", cat:"continuation", gen:"rounding_breakout", src:S.clas,
    one:"长时间横盘缩量沉淀后放量突破平台颈线，潜伏越久突破越强。",
    looks:["长时间(数月以上)窄幅横盘","横盘期极度缩量","放量突破平台颈线"],
    vol:["潜伏期地量","突破日放量(常放倍量)","突破后量价齐升"],
    mech:"长期沉淀筹码高度集中，地量说明无人交易，一旦放量突破动能释放猛烈。",
    buy:"放量突破平台颈线买入", stop:"跌破平台止损",
    fail:["突破后快速回到平台内=假突破"],
    pitfall:["潜伏过久丧失弹性","提前埋伏时间成本高"],
    related:["flat_base","rectangle_box","rounded_bottom"] },

  /* ================= 缺口 ================= */
  { id:"breakaway_gap", name:"突破缺口", alias:"Breakaway Gap", cat:"gap", gen:"breakaway_gap", src:S.clas,
    one:"突破盘整区/形态时出现的跳空缺口，预示新趋势启动，常不回补。",
    looks:["出现在盘整区或形态突破处","跳空缺口不被迅速回补","常伴随放量"],
    vol:["缺口当日放量","缺口上沿(向上)后续不被回补"],
    mech:"突破处多空力量失衡，跳空代表买力(或卖压)强势介入，新趋势启动。",
    buy:"向上突破缺口确认后买入(不回补)", stop:"缺口被回补则止损",
    fail:["缺口被快速回补=假突破"],
    pitfall:["把普通跳空当突破缺口"],
    related:["runaway_gap","island_top"] },

  { id:"runaway_gap", name:"中继缺口", alias:"测量缺口 / Runaway Gap", cat:"gap", gen:"runaway_gap", src:S.clas,
    one:"趋势中途出现的跳空缺口，预示趋势延续，可作为测量目标位。",
    looks:["出现在趋势中段(非突破处也非末端)","跳空不被迅速回补","趋势方向延续"],
    vol:["缺口当日放量","后续延续原趋势"],
    mech:"趋势中段买力(卖压)加速介入，缺口到趋势终点距离≈起点到缺口距离(测量法则)。",
    buy:"向上中继缺口可顺势加仓", stop:"缺口被回补止损",
    fail:["缺口被回补=趋势转弱"],
    pitfall:["与突破/衰竭缺口混淆"],
    related:["breakaway_gap","exhaustion_gap"] },

  { id:"exhaustion_gap", name:"衰竭缺口", alias:"Exhaustion Gap", cat:"gap", gen:"exhaustion_gap", src:S.clas,
    one:"趋势末段出现的跳空缺口，随后很快被回补，预示趋势衰竭反转。",
    looks:["出现在趋势加速末段","缺口很快被回补","回补后趋势反转"],
    vol:["缺口当日可能放量但随后量能不继","回补后反向放量"],
    mech:"末段追高/杀跌盘一次性释放，缺口被回补说明动能枯竭，趋势反转。",
    buy:"—（警惕反转）", stop:"缺口被回补后可反向操作，止损缺口外",
    fail:["缺口不被回补且趋势延续(则实为中继缺口)"],
    pitfall:["把衰竭缺口当中继缺口追单"],
    related:["runaway_gap","island_top"] },

  /* ================= 单根蜡烛 ================= */
  { id:"hammer", name:"锤子线", alias:"Hammer", cat:"single", gen:"hammer", src:S.nison,
    one:"下跌末段出现的小实体+长下影(下影为实体2-3倍)K线，见底反转信号。",
    looks:["小实体位于当日区间上部","下影线很长(2-3倍于实体)","上影线极短或没有","出现在下跌趋势中"],
    vol:"见底日可放量也可不放量，关键是位置。", mech:"下跌中抛压一次性释放后被买盘推回，长下影说明下方承接强。",
    buy:"次日确认(不创新低)后买入", stop:"止损锤子线最低点下方",
    fail:["次日跌破锤子线最低点=失败","出现在上涨中段则为上吊线(看跌)"],
    pitfall:["把上涨中的同形态当锤子线","不确认就追"],
    related:["hanging_man","dragonfly_doji","v_bottom"] },

  { id:"hanging_man", name:"上吊线", alias:"Hanging Man", cat:"single", gen:"hanging_man", src:S.nison,
    one:"上涨末段出现的小实体+长下影K线，见顶反转信号(锤子线的顶部版)。",
    looks:["小实体位于区间上部","下影线很长(2-3倍实体)","上影极短","出现在上涨趋势顶部"],
    vol:"见顶日放量更危险。", mech:"上涨中下方试探后被买回，但高位长下影说明抛压开始出现，见顶警示。",
    buy:"—（减仓/警惕）", stop:"次日跌破上吊线实体可做空，止损最高点上方",
    fail:["次日创新高则失效","出现在下跌中则为锤子线(看涨)"],
    pitfall:["与锤子线位置混淆"],
    related:["hammer","shooting_star","dragonfly_doji"] },

  { id:"inverted_hammer", name:"倒锤子线", alias:"Inverted Hammer", cat:"single", gen:"inverted_hammer", src:S.nison,
    one:"下跌末段出现的小实体+长上影K线，见底反转信号，需次日确认。",
    looks:["小实体位于区间下部","上影线很长(2-3倍实体)","下影极短","出现在下跌趋势中"],
    vol:"见底日量能可放量。", mech:"下跌中买盘一度上攻被空头压回，长上影说明买力开始试探，需次日确认。",
    buy:"次日大阳确认后买入", stop:"止损倒锤子线最低点下方",
    fail:["次日创新低=失败","无确认不追"],
    pitfall:["不确认就追","与流星线位置混淆"],
    related:["shooting_star","hammer"] },

  { id:"shooting_star", name:"流星线", alias:"射击之星 / Shooting Star", cat:"single", gen:"shooting_star", src:S.nison,
    one:"上涨末段出现的小实体+长上影K线，见顶反转信号。",
    looks:["小实体位于区间下部","上影线很长(2-3倍实体)","下影极短","出现在上涨趋势顶部"],
    vol:"见顶日放量更危险。", mech:"上涨中买盘上攻被空头打压回低位，长上影说明上方抛压重，见顶警示。",
    buy:"—（减仓/做空）", stop:"次日跌破实体可做空，止损最高点上方",
    fail:["次日创新高则失效"],
    pitfall:["与倒锤子线位置混淆"],
    related:["inverted_hammer","gravestone_doji","hanging_man"] },

  { id:"doji", name:"十字星", alias:"Doji", cat:"single", gen:"doji", src:S.nison,
    one:"开盘≈收盘的K线，多空均衡，位置决定方向(高位看跌/低位看涨)。",
    looks:["开盘价与收盘价几乎相等(实体极小)","上下影线长度可不一","出现在趋势中段或末端意义大"],
    vol:"十字星本身量能意义不大，看位置。", mech:"多空力量均衡、方向不定，趋势中段出现预示变盘，需后续方向确认。",
    buy:"次日方向确认后顺势", stop:"止损十字星影线外",
    fail:["次日延续原趋势则十字星仅作中继"],
    pitfall:["孤立看十字星不看位置"],
    related:["long_legged_doji","gravestone_doji","dragonfly_doji"] },

  { id:"long_legged_doji", name:"长腿十字", alias:"十字胎 / Long-legged Doji", cat:"single", gen:"long_legged_doji", src:S.nison,
    one:"上下影都很长的十字星，多空分歧剧烈，顶部出现更看跌。",
    looks:["开盘≈收盘(实体极小)","上下影线都很长","波动剧烈"],
    vol:"常放量。", mech:"当日多空双方大幅拉锯后回到原点，分歧极大，顶部出现警示反转。",
    buy:"—（警惕变盘）", stop:"次日方向确认后操作",
    fail:["次日延续原趋势则仅作中继"],
    pitfall:["忽视位置"],
    related:["doji","gravestone_doji"] },

  { id:"gravestone_doji", name:"墓碑十字", alias:"Gravestone Doji", cat:"single", gen:"gravestone_doji", src:S.nison,
    one:"开盘≈收盘在最低点、长上影的十字星，顶部出现看跌。",
    looks:["开盘≈收盘且位于当日最低点","长上影线","下影极短或无","出现在上涨顶部"],
    vol:"见顶日放量更危险。", mech:"买盘上攻被空头全数打回最低，上方抛压极重，顶部反转信号。",
    buy:"—（减仓/做空）", stop:"次日跌破可做空，止损上影高点上方",
    fail:["次日收回上影高点上方=失败"],
    pitfall:["与蜻蜓十字混淆(位置相反)"],
    related:["dragonfly_doji","shooting_star","doji"] },

  { id:"dragonfly_doji", name:"蜻蜓十字", alias:"Dragonfly Doji", cat:"single", gen:"dragonfly_doji", src:S.nison,
    one:"开盘≈收盘在最高点、长下影的十字星，底部出现看涨。",
    looks:["开盘≈收盘且位于当日最高点","长下影线","上影极短或无","出现在下跌底部"],
    vol:"见底日放量更佳。", mech:"卖盘下打被买盘全数推回最高，下方承接极强，底部反转信号。",
    buy:"次日确认后买入", stop:"止损下影低点下方",
    fail:["次日跌破下影低点=失败"],
    pitfall:["与墓碑十字混淆"],
    related:["hammer","gravestone_doji","doji"] },

  { id:"spinning_top", name:"陀螺线", alias:"Spinning Top", cat:"single", gen:"spinning_top", src:S.nison,
    one:"小实体+长上下影的K线，多空犹豫，常为中继或变盘前兆。",
    looks:["实体较小(但非十字)","上下影线都较长","反映多空拉锯"],
    vol:"量能意义不大。", mech:"多空激烈拉锯但谁也没占优，趋势中段多为中继，末端可能变盘。",
    buy:"—（观望/待方向）", stop:"方向确认后操作",
    fail:["次日延续原趋势则仅中继"],
    pitfall:["单独使用价值低"],
    related:["doji","long_legged_doji"] },

  { id:"marubozu_bull", name:"光头光脚阳线", alias:"Marubozu(阳)", cat:"single", gen:"marubozu_bull", src:S.nison,
    one:"无上下影的大阳线，开盘=最低、收盘=最高，强势买力信号。",
    looks:["大实体阳线","无上影无下影(开盘=最低，收盘=最高)","出现位置决定强弱"],
    vol:"常放量。", mech:"买盘从头到尾主导，无任何卖压回击，强势启动或加速。",
    buy:"顺势突破位出现可跟进", stop:"跌破阳线实体一半止损",
    fail:["次日大阴吞没则转弱"],
    pitfall:["高位长阳追高易被套"],
    related:["marubozu_bear","belt_hold_bull"] },

  { id:"marubozu_bear", name:"光头光脚阴线", alias:"Marubozu(阴)", cat:"single", gen:"marubozu_bear", src:S.nison,
    one:"无上下影的大阴线，开盘=最高、收盘=最低，强势卖力信号。",
    looks:["大实体阴线","无上下影(开盘=最高，收盘=最低)","出现位置决定强弱"],
    vol:"常放量。", mech:"卖盘从头到尾主导，无任何买力回击，强势下跌或加速。",
    buy:"—（回避/做空）", stop:"反包阳线可试空，止损阴线高点上方",
    fail:["次日大阳吞没则转强"],
    pitfall:["低位长阴恐慌杀跌易被反包"],
    related:["marubozu_bull","belt_hold_bear"] },

  { id:"belt_hold_bull", name:"看涨捉腰带", alias:"Belt Hold(阳)", cat:"single", gen:"belt_hold_bull", src:S.nison,
    one:"下跌后出现的光脚阳线(无下影)，捉腰带反转信号。",
    looks:["大阳线实体","无下影(或极短)","开盘即最低","出现在下跌后"],
    vol:"常放量。", mech:"下跌后买盘开盘即承接并一路推高，无下影说明无卖压回击，反转启动。",
    buy:"次日确认后买入", stop:"止损阳线最低点下方",
    fail:["次日跌破阳线最低=失败"],
    pitfall:["高位出现则非反转"],
    related:["marubozu_bull","belt_hold_bear"] },

  { id:"belt_hold_bear", name:"看跌捉腰带", alias:"Belt Hold(阴)", cat:"single", gen:"belt_hold_bear", src:S.nison,
    one:"上涨后出现的光头阴线(无上影)，捉腰带反转信号。",
    looks:["大阴线实体","无上影(或极短)","开盘即最高","出现在上涨后"],
    vol:"常放量。", mech:"上涨后卖盘开盘即打压并一路走低，无上影说明无买力回击，反转下跌。",
    buy:"—（减仓/做空）", stop:"次日跌破可做空，止损阴线高点上方",
    fail:["次日收回阴线高点上方=失败"],
    pitfall:["低位出现则非反转"],
    related:["marubozu_bear","belt_hold_bull"] },

  /* ================= 双蜡烛 ================= */
  { id:"bull_engulfing", name:"看涨吞没", alias:"Bullish Engulfing", cat:"two", gen:"bull_engulfing", src:S.nison,
    one:"下跌后大阳实体完全吞没前一根小阴实体，强势反转买点。",
    looks:["前一根小阴(下跌趋势中)","后一根大阳实体完全包住前一根实体","出现在下跌末段"],
    vol:"吞没阳线常放量。", mech:"下跌末段卖力衰竭，大阳吞没说明买力突然主导，反转信号。",
    buy:"吞没确认后买入", stop:"止损吞没阳线最低点下方",
    fail:["次日跌破吞没阳线最低=失败","吞没阳线被阴线吞没=失败"],
    pitfall:["非下跌趋势中吞没力度弱","实体未完全吞没不算"],
    related:["bear_engulfing","piercing","three_outside_up"] },

  { id:"bear_engulfing", name:"看跌吞没", alias:"Bearish Engulfing", cat:"two", gen:"bear_engulfing", src:S.nison,
    one:"上涨后大阴实体完全吞没前一根小阳实体，强势反转卖点。",
    looks:["前一根小阳(上涨趋势中)","后一根大阴实体完全包住前一根实体","出现在上涨末段"],
    vol:"吞没阴线常放量。", mech:"上涨末段买力衰竭，大阴吞没说明卖力突然主导，反转信号。",
    buy:"—（减仓/做空）", stop:"吞没确认可做空，止损吞没阴线最高点上方",
    fail:["次日收回吞没阴线最高=失败"],
    pitfall:["非上涨趋势中吞没力度弱"],
    related:["bull_engulfing","dark_cloud_cover","three_outside_down"] },

  { id:"piercing", name:"刺透形态", alias:"Piercing Pattern", cat:"two", gen:"piercing", src:S.nison,
    one:"下跌后第二根阳线开盘低于前阴最低、收盘回升到前阴实体中点之上，反转买点。",
    looks:["前一根长阴","后一根阳线开盘低于前阴最低","后阳收盘回升到前阴实体中点之上(但未吞没)"],
    vol:"刺透阳线常放量。", mech:"下跌中次日低开后被买力推回前阴中点之上，买力开始反攻，反转信号(弱于吞没)。",
    buy:"确认后买入", stop:"止损刺透阳线最低点下方",
    fail:["后阳收盘未到前阴中点=失败","次日跌破刺透阳线最低=失败"],
    pitfall:["收盘不到中点不算刺透"],
    related:["bull_engulfing","dark_cloud_cover"] },

  { id:"dark_cloud_cover", name:"乌云盖顶", alias:"Dark Cloud Cover", cat:"two", gen:"dark_cloud_cover", src:S.nison,
    one:"上涨后第二根阴线开盘高于前阳最高、收盘回落到前阳实体中点之下，反转卖点。",
    looks:["前一根长阳","后一根阴线开盘高于前阳最高","后阴收盘回落到前阳实体中点之下(但未吞没)"],
    vol:"盖顶阴线常放量。", mech:"上涨中次日高开后被卖力打回前阳中点之下，卖力开始反攻，反转信号。",
    buy:"—（减仓/做空）", stop:"确认可做空，止损盖顶阴线最高点上方",
    fail:["后阴收盘未到前阳中点下=失败"],
    pitfall:["收盘不到中点不算"],
    related:["bear_engulfing","piercing"] },

  { id:"harami_bull", name:"看涨孕线", alias:"Bullish Harami", cat:"two", gen:"harami_bull", src:S.nison,
    one:"下跌后前一根大阴包住后一根小阳(小阳在前阴实体内)，动能衰减反转信号。",
    looks:["前一根大阴","后一根小阳实体完全在前阴实体之内","出现在下跌趋势中"],
    vol:"孕线量能常缩。", mech:"大阴后出现小阳孕出，卖力骤减、动能衰减，反转前兆(需确认)。",
    buy:"—（待确认/轻仓试多）", stop:"止损前阴最低点下方",
    fail:["次日跌破前阴最低=失败","孕出小阳被吞没=失败"],
    pitfall:["孕线力度弱、需次日确认","单独孕线即追"],
    related:["harami_bear","doji_harami","three_inside_up"] },

  { id:"harami_bear", name:"看跌孕线", alias:"Bearish Harami", cat:"two", gen:"harami_bear", src:S.nison,
    one:"上涨后前一根大阳包住后一根小阴(小阴在前阳实体内)，动能衰减反转信号。",
    looks:["前一根大阳","后一根小阴实体完全在前阳实体之内","出现在上涨趋势中"],
    vol:"孕线量能常缩。", mech:"大阳后出现小阴孕出，买力骤减、动能衰减，反转前兆(需确认)。",
    buy:"—（待确认/减仓）", stop:"止损前阳最高点上方",
    fail:["次日突破前阳最高=失败"],
    pitfall:["孕线力度弱、需确认"],
    related:["harami_bull","doji_harami","three_inside_down"] },

  { id:"doji_harami", name:"十字孕线", alias:"Doji Harami", cat:"two", gen:"doji_harami", src:S.nison,
    one:"前一根大实体包住后一根十字星，是比普通孕线更强的变盘信号。",
    looks:["前一根大实体(阳或阴)","后一根十字星在前实体之内","出现在趋势中"],
    vol:"—", mech:"大实体后出现十字，多空由一方主导转为均衡，重要变盘前兆。",
    buy:"—（待方向确认）", stop:"方向确认后操作",
    fail:["次日延续原趋势则失效"],
    pitfall:["忽略位置"],
    related:["harami_bull","harami_bear","doji"] },

  { id:"counterattack_bull", name:"看涨反击线", alias:"Bullish Counterattack", cat:"two", gen:"counterattack_bull", src:S.nison,
    one:"下跌中前阴大阴、后一根低开但收盘回到前阴收盘价附近，反转信号。",
    looks:["前一根大阴","后一根低开但强势收回，收盘≈前阴收盘","出现在下跌趋势中"],
    vol:"反击阳线常放量。", mech:"下跌中次日低开后买力强力反攻收回前收附近，多空力量瞬间逆转。",
    buy:"—（待确认/轻仓）", stop:"止损前阴最低下方",
    fail:["次日跌破前阴最低=失败"],
    pitfall:["反击未到前收附近不算"],
    related:["counterattack_bear","piercing"] },

  { id:"counterattack_bear", name:"看跌反击线", alias:"Bearish Counterattack", cat:"two", gen:"counterattack_bear", src:S.nison,
    one:"上涨中前阳大阳、后一根高开但收盘回到前阳收盘价附近，反转信号。",
    looks:["前一根大阳","后一根高开但被打回，收盘≈前阳收盘","出现在上涨趋势中"],
    vol:"反击阴线常放量。", mech:"上涨中次日高开后卖力强力反打收回前收附近，多空力量瞬间逆转。",
    buy:"—（减仓/待确认）", stop:"止损前阳最高上方",
    fail:["次日突破前阳最高=失败"],
    pitfall:["反击未到前收附近不算"],
    related:["counterattack_bull","dark_cloud_cover"] },

  { id:"homing_pigeon", name:"鸽子线", alias:"Homing Pigeon", cat:"two", gen:"homing_pigeon", src:S.nison,
    one:"下跌中前大阴包住后小阴(双阴孕)，抛压减弱的反转前兆。",
    looks:["前一根大阴","后一根小阴在前阴实体内","两根都是阴线","出现在下跌趋势中"],
    vol:"孕线量能常缩。", mech:"大阴后小阴孕出，虽然都收阴但抛压明显减弱，反转前兆(弱于阳孕)。",
    buy:"—（待确认）", stop:"止损前阴最低下方",
    fail:["次日跌破前阴最低=失败"],
    pitfall:["两阴孕出力度弱于阳孕"],
    related:["harami_bull","harami_bear"] },

  { id:"separating_bull", name:"向上分离线", alias:"Separating Lines(阳)", cat:"two", gen:"separating_bull", src:S.nison,
    one:"上涨中两根同向阳线、第二根跳空高开且方向一致，趋势持续信号。",
    looks:["前一根阳线","后一根阳线跳空高开","两根方向一致","出现在上涨趋势中"],
    vol:"分离阳线常放量。", mech:"上涨中买力持续跳空介入，趋势延续。",
    buy:"顺势加仓", stop:"止损前阳最低下方",
    fail:["次日跳空回补=趋势转弱"],
    pitfall:["把跳空缺口当分离线而忽视趋势背景"],
    related:["bull_engulfing","marubozu_bull"] },

  /* ================= 三蜡烛 ================= */
  { id:"morning_star", name:"晨星", alias:"Morning Star", cat:"three", gen:"morning_star", src:S.nison,
    one:"下跌中'长阴+十字/小实体+大阳'组合，大阳收复第一根中点之上，见底反转。",
    looks:["第一根长阴","第二根十字或小实体(与前阴有缺口更佳)","第三根大阳收盘回到第一根实体中点之上"],
    vol:"第三根大阳常放量。", mech:"下跌动能衰竭(十字)、买力反攻(大阳)，三根组合确认反转。",
    buy:"第三根大阳确认后买入", stop:"止损晨星最低点下方",
    fail:["第三根未收复第一根中点=失败","次日跌破组合最低=失败"],
    pitfall:["第三根力度不足则偏弱"],
    related:["evening_star","abandoned_baby_bull","three_white_soldiers"] },

  { id:"evening_star", name:"黄昏星", alias:"Evening Star", cat:"three", gen:"evening_star", src:S.nison,
    one:"上涨中'长阳+十字/小实体+大阴'组合，大阴跌回第一根中点之下，见顶反转。",
    looks:["第一根长阳","第二根十字或小实体","第三根大阴收盘跌回第一根实体中点之下"],
    vol:"第三根大阴常放量。", mech:"上涨动能衰竭(十字)、卖力反攻(大阴)，三根组合确认反转。",
    buy:"—（减仓/做空）", stop:"第三根大阴确认可做空，止损组合最高上方",
    fail:["第三根未跌回第一根中点=失败"],
    pitfall:["第三根力度不足则偏弱"],
    related:["morning_star","abandoned_baby_bear","three_black_crows"] },

  { id:"three_white_soldiers", name:"红三兵", alias:"三白兵 / Three White Soldiers", cat:"three", gen:"three_white_soldiers", src:S.nison,
    one:"三根连续递增的阳线，每根收盘创新高、开盘在前根实体内，推升反转。",
    looks:["三根连续阳线","每根收盘高于前根收盘","每根开盘在前根实体内(或附近)","出现在底部反转"],
    vol:"三阳量能温和放大最佳。", mech:"买力持续三 日 推升，无明显卖压回击，底部反转确认。",
    buy:"第三根确认后顺势买入", stop:"止损第一根阳线最低下方",
    fail:["第三根长上影滞涨=三兵受阻","后续大阴吞没=失败"],
    pitfall:["三阳过大过陡后追高易被套(三兵受阻)"],
    related:["three_black_crows","three_inside_up","three_outside_up"] },

  { id:"three_black_crows", name:"三乌鸦", alias:"黑三兵 / Three Black Crows", cat:"three", gen:"three_black_crows", src:S.nison,
    one:"三根连续递减的阴线，每根收盘创新低、开盘在前根实体内，推低反转。",
    looks:["三根连续阴线","每根收盘低于前根收盘","每根开盘在前根实体内","出现在顶部反转"],
    vol:"三阴量能温和放大最佳。", mech:"卖力持续三日推低，无明显买力回击，顶部反转确认。",
    buy:"—（减仓/做空）", stop:"止损第一根阴线最高上方",
    fail:["后续大阳吞没=失败"],
    pitfall:["三阴过长后杀跌易被反包"],
    related:["three_white_soldiers","three_inside_down","three_outside_down"] },

  { id:"three_inside_up", name:"三内升", alias:"Three Inside Up", cat:"three", gen:"three_inside_up", src:S.nison,
    one:"看涨孕线+第三根大阳确认，孕线反转的确认形态。",
    looks:["前两根构成看涨孕线(大阴包小阳)","第三根大阳收盘创新高(超过第一根)"],
    vol:"第三根大阳放量。", mech:"孕线后第三根大阳确认反转，比单独孕线更可靠。",
    buy:"第三根大阳确认后买入", stop:"止损组合最低下方",
    fail:["第三根未创新高=失败"],
    pitfall:["第三根力度不足"],
    related:["harami_bull","three_outside_up","morning_star"] },

  { id:"three_inside_down", name:"三内降", alias:"Three Inside Down", cat:"three", gen:"three_inside_down", src:S.nison,
    one:"看跌孕线+第三根大阴确认，孕线反转的确认形态。",
    looks:["前两根构成看跌孕线(大阳包小阴)","第三根大阴收盘创新低(低于第一根)"],
    vol:"第三根大阴放量。", mech:"孕线后第三根大阴确认反转。",
    buy:"—（减仓/做空）", stop:"止损组合最高上方",
    fail:["第三根未创新低=失败"],
    pitfall:["第三根力度不足"],
    related:["harami_bear","three_outside_down","evening_star"] },

  { id:"three_outside_up", name:"三外升", alias:"Three Outside Up", cat:"three", gen:"three_outside_up", src:S.nison,
    one:"看涨吞没+第三根大阳确认，吞没反转的确认形态。",
    looks:["前两根构成看涨吞没(大阳吞小阴)","第三根大阳收盘创新高"],
    vol:"第三根大阳放量。", mech:"吞没后第三根大阳确认反转，比单独吞没更可靠。",
    buy:"第三根大阳确认后买入", stop:"止损组合最低下方",
    fail:["第三根未创新高=失败"],
    pitfall:["第三根力度不足"],
    related:["bull_engulfing","three_inside_up","three_white_soldiers"] },

  { id:"three_outside_down", name:"三外降", alias:"Three Outside Down", cat:"three", gen:"three_outside_down", src:S.nison,
    one:"看跌吞没+第三根大阴确认，吞没反转的确认形态。",
    looks:["前两根构成看跌吞没(大阴吞小阳)","第三根大阴收盘创新低"],
    vol:"第三根大阴放量。", mech:"吞没后第三根大阴确认反转。",
    buy:"—（减仓/做空）", stop:"止损组合最高上方",
    fail:["第三根未创新低=失败"],
    pitfall:["第三根力度不足"],
    related:["bear_engulfing","three_inside_down","three_black_crows"] },

  { id:"rising_three_methods", name:"上升三法", alias:"Rising Three Methods", cat:"three", gen:"rising_three_methods", src:S.nison,
    one:"大阳+三根回落小阴(不破第一根大阳区间)+大阳续攻，持续看涨形态。",
    looks:["第一根大阳","中间三根小阴逐步回落但全部在第一根大阳区间内","第五根大阳收盘创新高"],
    vol:"中间三小阴缩量、两头大阳放量。", mech:"大阳后小幅回落洗盘但不出新低，再次大阳确认趋势延续。",
    buy:"第五根大阳确认后顺势加仓", stop:"止损第一根大阳最低下方",
    fail:["中间小阴跌破第一根大阳最低=失败","第五根未创新高=失败"],
    pitfall:["中间回落过深则偏弱"],
    related:["falling_three_methods","three_white_soldiers"] },

  { id:"falling_three_methods", name:"下降三法", alias:"Falling Three Methods", cat:"three", gen:"falling_three_methods", src:S.nison,
    one:"大阴+三根反弹小阳(不破第一根大阴区间)+大阴续跌，持续看跌形态。",
    looks:["第一根大阴","中间三根小阳逐步反弹但全部在第一根大阴区间内","第五根大阴收盘创新低"],
    vol:"中间三小阳缩量、两头大阴放量。", mech:"大阴后小幅反弹但不出新高，再次大阴确认趋势延续下跌。",
    buy:"—（回避/做空）", stop:"止损第一根大阴最高上方",
    fail:["中间小阳突破第一根大阴最高=失败","第五根未创新低=失败"],
    pitfall:["中间反弹过强则偏弱"],
    related:["rising_three_methods","three_black_crows"] },

  { id:"abandoned_baby_bull", name:"弃婴底", alias:"Abandoned Baby(底)", cat:"three", gen:"abandoned_baby_bull", src:S.nison,
    one:"下跌中'长阴+跳空十字+跳空大阳'，十字被两侧缺口隔离，强反转见底。",
    looks:["第一根长阴","第二根跳空低开的十字星(与前后均有缺口)","第三根跳空高开大阳","十字被两侧缺口隔离成孤岛"],
    vol:"—", mech:"下跌末段跳空十字反映极度恐慌与多空均衡，第三根跳空大阳确认买力主导，强反转。",
    buy:"第三根大阳确认后买入", stop:"止损十字星最低下方",
    fail:["缺口被回补=形态破坏"],
    pitfall:["缺口不成立则非弃婴"],
    related:["morning_star","island_bottom","abandoned_baby_bear"] },

  { id:"abandoned_baby_bear", name:"弃婴顶", alias:"Abandoned Baby(顶)", cat:"three", gen:"abandoned_baby_bear", src:S.nison,
    one:"上涨中'长阳+跳空十字+跳空大阴'，十字被两侧缺口隔离，强反转见顶。",
    looks:["第一根长阳","第二根跳空高开的十字星(与前后均有缺口)","第三根跳空低开大阴","十字被两侧缺口隔离"],
    vol:"—", mech:"上涨末段跳空十字反映极度追高与多空均衡，第三根跳空大阴确认卖力主导，强反转。",
    buy:"—（减仓/做空）", stop:"止损十字星最高上方",
    fail:["缺口被回补=形态破坏"],
    pitfall:["缺口不成立则非弃婴"],
    related:["evening_star","island_top","abandoned_baby_bull"] },

  { id:"upside_gap_two_crows", name:"向上跳空两乌鸦", alias:"Upside Gap Two Crows", cat:"three", gen:"upside_gap_two_crows", src:S.nison,
    one:"上涨中跳空后两根阴线、第二根吞没第一根，顶部反转警示。",
    looks:["第一根长阳","第二根跳空高开阴线","第三根阴线吞没第二根阴线","出现在上涨趋势中"],
    vol:"—", mech:"上涨中跳空后连续两根阴线且第二根吞没，说明追高盘被持续打压，顶部警示。",
    buy:"—（减仓/警惕）", stop:"第三根大阴确认可做空，止损最高上方",
    fail:["后续大阳收回则失败"],
    pitfall:["两阴未吞没则力度弱"],
    related:["evening_star","three_black_crows"] },

  /* ================= 体系 / 指标 ================= */
  { id:"livermore_pivotal", name:"利弗莫尔关键点", alias:"Pivotal Point", cat:"system", gen:"livermore_pivotal", src:S.liver,
    one:"利弗莫尔核心：耐心等待'关键点'突破顺势进场，用时间验证趋势。",
    looks:["价格在关键点(前高/前低/整理端点)下方蓄势","放量突破关键点","突破后快速向有利方向运行"],
    vol:["突破关键点放量","突破后行情应快速展开","若突破后迟滞=危险信号"],
    mech:"关键点代表市场'最小阻力线'选择方向的时刻，突破即顺势进场，时间验证有效性。",
    buy:"放量突破关键点顺势买入", stop:"突破后迟滞或跌回关键点下方止损",
    fail:["突破后迟滞不涨=危险信号","跌破关键点=最小阻力向下"],
    pitfall:["提前埋伏而非等突破","突破后迟滞不止损"],
    related:["cup_handle","breakaway_gap","donchian_turtle"] },

  { id:"wyckoff_accumulation", name:"威科夫吸筹(弹簧)", alias:"Wyckoff Spring", cat:"system", gen:"wyckoff_accumulation", src:S.wyk,
    one:"威科夫吸筹末段的Spring：假跌破支撑扫止损后回收，是主升前的最后洗盘买点。",
    looks:["PS抛售→SC抛售高潮放量→AR自动反弹→ST二次测试→Spring假跌破支撑→LPS最后支撑点→SOS主升",
           "Spring跌破前期支撑后快速回收","LPS为加仓点，SOS为主升确认"],
    vol:["SC放量抛售","测试期缩量","Spring可缩量可放量但快速回收","主升放量"],
    mech:"主力在吸筹末段用Spring击穿支撑触发散户止损、吸收最后筹码，随后主升。",
    buy:"Spring回收后/LPS回踩不破加仓", stop:"止损Spring最低点下方",
    fail:["Spring跌破后不回收=真跌破","主升无量=偏弱"],
    pitfall:["把真跌破当Spring","LPS未确认就重仓"],
    related:["wyckoff_distribution","cup_handle","double_bottom"] },

  { id:"wyckoff_distribution", name:"威科夫派发(上冲)", alias:"Wyckoff UT(上冲)", cat:"system", gen:"wyckoff_distribution", src:S.wyk,
    one:"威科夫派发末段的UT上冲：假突破阻力扫空单后回落，是主跌前的最后派发卖点。",
    looks:["BC购买高潮→AR自动回落→UT假突破阻力→LPSY最后供给点→下跌",
           "UT突破阻力后快速回落","LPSY为加空点"],
    vol:["BC放量购买","测试期缩量","UT可放量但快速回落","下跌放量"],
    mech:"主力在派发末段用UT击穿阻力触发散户追高/空单止损、派发最后筹码，随后主跌。",
    buy:"—（做空/减仓）", stop:"UT假突破回落确认做空，止损UT最高上方",
    fail:["UT突破后不回落=真突破","主跌无量=偏弱"],
    pitfall:["把真突破当UT","LPSY未确认就重仓空"],
    related:["wyckoff_accumulation","double_top","head_shoulders_top"] },

  { id:"elliott_wave", name:"艾略特波浪", alias:"Elliott Wave", cat:"system", gen:"elliott_wave", src:S.ellio,
    one:"主升浪5浪(1-2-3-4-5)+修正3浪(A-B-C)，3浪常最长、不可破1浪底，数浪顺势。",
    looks:["1浪启动→2浪回调(不破1浪底)→3浪主升(最长)→4浪回调(不破1浪顶)→5浪末段→A-B-C修正",
           "2浪不破1浪底、4浪不破1浪顶是铁律","3浪常为最长最强"],
    vol:["1浪温和、3浪放量、5浪常量价背离","修正浪缩量"],
    mech:"市场情绪以5上3下的波浪结构演进，波浪理论提供趋势阶段与目标位的框架。",
    buy:"2浪末段(1浪底上方)买入、3浪主升加仓", stop:"2浪跌破1浪底则数浪失败止损",
    fail:["2浪破1浪底、4浪破1浪顶=数浪失败","5浪失败(不创新高)"],
    pitfall:["数浪主观性强、易事后修正","过度追求精确数浪"],
    related:["chanlun","livermore_pivotal"] },

  { id:"chanlun", name:"缠论", alias:"缠中说禅", cat:"system", gen:"chanlun", src:S.chan,
    one:"以中枢为核心：走势类型+中枢+背驰，给出一二三类买卖点。",
    looks:["走势由中枢(至少三段次级别重叠区间)构成","背驰=动能衰竭(顶/底背驰)","一类买卖点=背驰转折、二类=回试不破、三类=中枢上沿突破回踩不破"],
    vol:["背驰常伴量能背离","三类买点回踩缩量、突破放量"],
    mech:"走势完美定律：任何走势终将完成；背驰判定转折，三类买卖点给出精确进出场。",
    buy:"一类买卖点(背驰转折)、二类(回试)、三类(中枢上沿)", stop:"一类买点止损背驰段最低下方",
    fail:["背驰后再背驰(小转大)需小级别确认","中枢扩展升级"],
    pitfall:["背驰判定需结合级别","把任何震荡都当中枢"],
    related:["elliott_wave","wyckoff_accumulation","obv_divergence"] },

  { id:"granville_ma", name:"葛兰碧均线八法则", alias:"Granville's 8 Rules", cat:"system", gen:"granville_ma", src:S.gran,
    one:"葛兰碧均线四大买点(金叉/回踩不破/乖离修复/再加速)与四大卖点。",
    looks:["4买：①均线上翘价突破、②回踩均线不破、③乖离过大修复后、④再加速",
           "4卖：①均线下弯价跌破、②反抽均线不过、③乖离过大反弹后、④再加速下跌"],
    vol:["金叉/突破放量","回踩缩量、再加速放量"],
    mech:"以均线为趋势与支撑/阻力，结合乖离率判断超买超卖，给出买卖规则。",
    buy:"①②④买点顺势买入", stop:"跌破均线(下弯)止损",
    fail:["横盘期均线反复缠绕、信号失灵"],
    pitfall:["横盘期频繁触发假信号","忽视均线方向(上翘/下弯)"],
    related:["ma_bullish_alignment","macd_golden_cross","bollinger_squeeze"] },

  { id:"ma_bullish_alignment", name:"均线多头排列", alias:"MA Bullish Stack", cat:"system", gen:"ma_bullish_alignment", src:S.clas,
    one:"短>中>长均线依次向上、价格在最上方，强势多头趋势，回踩短均线即买点。",
    looks:["价格>短期MA>中期MA>长期MA","各均线方向向上","呈多头排列"],
    vol:["回踩短均线缩量、再上量价齐升"],
    mech:"多周期同向向上反映各级别买力一致，强势趋势确立，回踩短均线是顺势加仓点。",
    buy:"回踩短期均线不破买入", stop:"短期均线下穿中期均线(多头瓦解)止损",
    fail:["短期均线下穿中期均线=多头瓦解","价格跌破长期均线=转势"],
    pitfall:["均线过近时多头排列弱","高位乖离过大追多"],
    related:["ma_bearish_alignment","granville_ma","macd_golden_cross"] },

  { id:"ma_bearish_alignment", name:"均线空头排列", alias:"MA Bearish Stack", cat:"system", gen:"ma_bearish_alignment", src:S.clas,
    one:"短<中<长均线依次向下、价格在最下方，强势空头趋势，反抽短均线即卖点。",
    looks:["价格<短期MA<中期MA<长期MA","各均线方向向下","呈空头排列"],
    vol:["反抽短均线缩量、再下量增"],
    mech:"多周期同向向下反映各级别卖力一致，强势下跌趋势，反抽短均线是顺势做空点。",
    buy:"—（回避/做空）", stop:"短期均线上穿中期均线(空头瓦解)离场",
    fail:["短期均线上穿中期均线=空头瓦解"],
    pitfall:["低位乖离过大杀跌"],
    related:["ma_bullish_alignment","macd_death_cross"] },

  { id:"macd_golden_cross", name:"MACD金叉", alias:"MACD Golden Cross", cat:"system", gen:"macd_golden_cross", src:S.gran,
    one:"快线(DIF)上穿慢线(DEA)，红柱放大，趋势转多的中线买点。",
    looks:["DIF由下上穿DEA","柱状图由绿翻红并放大","零轴上方金叉更可靠"],
    vol:"金叉常伴量能放大。", mech:"短期动量由弱转强、领先中长期，金叉为转多信号，红柱放大确认动能。",
    buy:"金叉(零轴上方更佳)买入", stop:"DIF再下穿DEA(死叉)止损",
    fail:["零轴下方金叉力度弱、易反复","金叉后红柱不放大=动能不足"],
    pitfall:["零轴下方金叉易假金叉","金叉位置过高追高"],
    related:["macd_death_cross","ma_bullish_alignment","granville_ma"] },

  { id:"macd_death_cross", name:"MACD死叉", alias:"MACD Death Cross", cat:"system", gen:"macd_death_cross", src:S.gran,
    one:"快线(DIF)下穿慢线(DEA)，绿柱放大，趋势转空的中线卖点。",
    looks:["DIF由上下穿DEA","柱状图由红翻绿并放大","零轴下方死叉更可靠"],
    vol:"死叉常伴量能放大。", mech:"短期动量由强转弱，死叉为转空信号，绿柱放大确认动能。",
    buy:"—（减仓/做空）", stop:"DIF再上穿DEA(金叉)离场",
    fail:["零轴上方死叉力度弱、易反复"],
    pitfall:["零轴上方死叉易假死叉"],
    related:["macd_golden_cross","ma_bearish_alignment"] },

  { id:"bollinger_squeeze", name:"布林带收口突破", alias:"Bollinger Squeeze", cat:"system", gen:"bollinger_squeeze", src:S.boll,
    one:"布林带极度收口(波动收敛)后开口扩张突破，常爆发单边趋势。",
    looks:["上下轨极度收窄(波动收敛)","收口期量能萎缩","开口突破方向放量"],
    vol:"收口期缩量、开口突破放量。", mech:"收口反映波动压缩、动能积蓄，开口扩张即动能释放，方向即趋势方向。",
    buy:"开口向上突破上轨买入", stop:"收回中轨止损",
    fail:["开口后迅速收回中轨=假突破","收口时间不足则力度弱"],
    pitfall:["收口期提前埋伏易被反复打","未确认方向就追"],
    related:["donchian_turtle","breakaway_gap","symmetric_triangle"] },

  { id:"donchian_turtle", name:"海龟/唐奇安突破", alias:"Donchian / Turtle", cat:"system", gen:"donchian_turtle", src:S.turtle,
    one:"海龟交易法核心：突破N日(20日)高低点入场，跌破10日低点离场，趋势跟踪系统。",
    looks:["N日(默认20日)新高通道与N日新低通道","突破20日高点买入、跌破10日低点卖出","通道随行情扩张"],
    vol:"突破常伴量能放大。", mech:"唐奇安通道捕捉趋势突破，海龟以机械化规则截断亏损、让利润奔跑。",
    buy:"突破20日新高买入", stop:"跌破10日低点止损",
    fail:["横盘期频繁假突破(海龟以小亏试错换大趋势)"],
    pitfall:["无法承受连续小亏则不适合趋势跟踪","参数不统一则回测失真"],
    related:["bollinger_squeeze","livermore_pivotal","breakaway_gap"] },

  { id:"gann_angles", name:"江恩角度线", alias:"Gann Angles", cat:"system", gen:"gann_angles", src:S.gann,
    one:"江恩以角度(1×1=45°为主)衡量价格与时间平衡，回踩角度线为买卖点。",
    looks:["从重要低点/高点引出1×1(45°)、2×1、1×2等角度线","价格沿/回踩角度线运行","1×1为趋势主平衡线"],
    vol:"—", mech:"江恩认为价格与时间存在几何平衡，角度线提供支撑阻力与买卖时点。",
    buy:"回踩1×1角度线不破买入", stop:"跌破1×1角度线止损",
    fail:["跌破1×1角度线=趋势转弱"],
    pitfall:["角度线需正确时间-价格比例标定","过度依赖角度而忽视其他"],
    related:["elliott_wave","livermore_pivotal"] },

  { id:"obv_divergence", name:"OBV顶背离", alias:"OBV Divergence", cat:"system", gen:"obv_divergence", src:S.gran,
    one:"价格创新高但OBV不创新高(量能不配合)，顶部背离警示反转。",
    looks:["价格逐波创新高","OBV逐波不创新高(量能萎缩)","价升量不增"],
    vol:"价格新高但量能递减是核心。", mech:"价格虚高而买盘实量不足，OBV(能量潮)先于价格转弱，背离预示顶部。",
    buy:"—（减仓/警惕）", stop:"价格跌破前低确认反转止损/做空",
    fail:["背离后再背离(趋势延续)需多次确认"],
    pitfall:["单一背离即反转、忽视大趋势"],
    related:["chanlun","granville_ma","head_shoulders_top"] },

  { id:"volume_price_spring", name:"量价弹簧(放量洗盘)", alias:"Volume Price Spring", cat:"system", gen:"volume_price_spring", src:S.wyk,
    one:"放量下杀制造恐慌后缩量企稳、放量收复，弹簧式洗盘买点。",
    looks:["放量下杀(恐慌底)","缩量企稳(抛压衰竭)","放量收复(买力回归)"],
    vol:["下杀放量、企稳缩量、收复放量","量价关系是核心"],
    mech:"主力用放量下杀触发散户止损、清洗浮筹，缩量企稳后放量收复启动行情。",
    buy:"放量收复恐慌底时买入", stop:"止损恐慌底最低下方",
    fail:["收复失败再破低=延续下跌","收复无量=偏弱"],
    pitfall:["把真破位当洗盘","恐慌底未企稳就抄"],
    related:["wyckoff_accumulation","v_bottom","double_bottom"] },

  { id:"wyckoff_no_demand", name:"威科夫无需求上冲", alias:"No Demand(UT弱化)", cat:"system", gen:"wyckoff_no_demand", src:S.wyk,
    one:"阻力位缩量上推(无需求)后失败回落，是弱势反弹见顶的卖点。",
    looks:["价格反抽阻力位","反抽缩量(无需求)","缩量滞涨后回落跌破"],
    vol:"反抽缩量是核心。", mech:"反抽阻力却无买力(量缩)，说明需求不足，一旦失守即下跌。",
    buy:"—（减仓/做空）", stop:"缩量滞涨后跌破可做空，止损阻力位上方",
    fail:["反抽放量突破阻力=有效突破"],
    pitfall:["把缩量反抽当蓄势"],
    related:["wyckoff_distribution","head_shoulders_top","double_top"] },

  { id:"trap_double_top_fail", name:"假双顶(未确认)", alias:"Failed Double Top", cat:"system", gen:"trap_double_top_fail", src:S.clas,
    one:"疑似双顶但未跌破颈线即放量突破前高，形态失败转为续涨，警示左侧做空的陷阱。",
    looks:["出现两个相近高点(疑似双顶)","颈线未被跌破","随后放量突破前高=形态失败"],
    vol:"突破前高放量是确认。", mech:"未跌破颈线前双顶不成立，放量突破前高说明卖压未接管、趋势延续。",
    buy:"放量突破前高确认后顺势买入", stop:"止损双顶高点下方",
    fail:["跌破颈线则成立为真双顶"],
    pitfall:["未确认即左侧做空是常见陷阱","把疑似形态当确认形态"],
    related:["double_top","cup_handle","livermore_pivotal"] }

  ];

  global.STOCK = {
    CATEGORIES: CATEGORIES,
    MODELS: MODELS,
    byId: function (id) { return MODELS.find(function (m) { return m.id === id; }); }
  };
})(window);
